"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def fibonacci():
    num1 = 0
    num2 = 1
    while True:
        num1 = num1 + num2
        num2 = num2 + num1
        if num1 <= 4000000:
            yield num1
        else:
            return
        if num1 <= 4000000:
            yield num2
        else:
            return


sum = 0
for fib in fibonacci():
    if fib % 2 == 0:
        sum += fib
print sum

